name: Update latest Extensions documentation in the website

on:
  push:
    branches:
      - 'master'
    paths:
      - 'docs/*.md'

jobs:
  Make-PR:
    name: Make PR on website repository with updated latest Extensions documentation
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout Current repository
        uses: actions/checkout@v3
        with:
          path: extensions
      - name: Checkout Another repository
        uses: actions/checkout@v3
        with:
          repository: asyncapi/website
          path: website
          token: ${{ env.GITHUB_TOKEN }}
      - name: Config git
        run: |
          git config --global user.name asyncapi-bot
          git config --global user.email info@asyncapi.io
      - name: Create branch
        working-directory: ./website
        run: |
          git checkout -b update-extensions-docs-${{ github.sha }}
      - name: Copy extensions folder from Current Repo to Another
        working-directory: ./website
        run: |
          mkdir -p ./pages/docs/reference/extensions
          printf "%s\ntitle: Extensions\nweight: 10\n%s" "---" "---"> ../extensions-catalog/extensions/_section.md
          mv ../extensions-catalog/extensions/*.md ./pages/docs/reference/extensions
      - name: 
        working-directory: ./website
        run: 
      - uses: actions/github-script@v4
        with:
          script: |
            const { writeFile } = require('fs');
            var slug = {
              "value": "reference/extensions/",
              "href": "https://github.com/asyncapi/extensions-catalog/tree/master/extensions"
            };
            const data = require('./config/edit-page-config.json');
            const checkSlug="reference/extensions/"
            flag=0;
            data.map(function (item){
              if(item.value==checkSlug) flag=1; 
            })
            if(flag==0){ 
            data.push(slug);
            const path = './config/edit-page-config.json';
              writeFile(path, JSON.stringify(data,null,2), (error) => {
                if (error) {
                  console.log('An error has occurred ', error);
                  return;
                }
              })
            }
      - name: Commit and push
        working-directory: ./website
        run: |
          git add .
          git commit -m "docs(extension): update latest extensions docs"
          git push https://${{ env.GITHUB_TOKEN }}@github.com/asyncapi/website
      - name: Create PR
        working-directory: ./website
        run: |
          gh pr create --title "docs(extensions): update latest extensions documentation" --body "Updated extensions documentation is available and this PR introduces update to extensions folder on the website" --head "update-extensions-docs-${{ github.sha }}"